version: '3'
services:
  web:
    container_name: battery-monitor
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=$PORT
      - DATATBASE_URL=$DATABASE_URL
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
